=== jejking/authorsite-old/old/authorsite/src/xml/languageSchema.xsd
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!--
 * Copyright (C) 2003  John King
 *
 * This file is part of the authorsite.org bibliographic
 * application.
 *
 * This application is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
        
        <xs:simpleType name="iso639Type">
                <xs:restriction base="xs:ID">
                        <xs:minLength value="3"/>
                        <xs:maxLength value="3"/>
                </xs:restriction>
        </xs:simpleType>
        
        <xs:simpleType name="priorityType">
                <xs:restriction base="xs:positiveInteger">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="3"/>
                </xs:restriction>
        </xs:simpleType>
        
        <xs:element name="language">
                <xs:complexType>
                        <xs:attribute name="iso639" type="iso639Type" use="required"/>
                        <xs:attribute name="priority" type="priorityType" use="required"/>
                        <xs:attribute name="engName" type="xs:string" use="required"/>
                </xs:complexType>
        </xs:element>
        
        <xs:element name="langlist">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element ref="language" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                </xs:complexType>
                <xs:unique name="English">
                        <xs:selector xpath="language"/>
                        <xs:field xpath="@engName"/>
                </xs:unique>
        </xs:element>
</xs:schema>

=== jejking/authorsite-old/old/MailArchive/src/languages.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!--
 * Copyright (C) 2003  John King
 *
 * This file is part of the authorsite.org bibliographic
 * application.
 *
 * This application is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 -->
<!-- 
$Header: /cvsroot/authorsite/MailArchive/src/languages.xml,v 1.1.1.1 2004/03/09 23:18:41 jejking Exp $
This is the language list for the authorsite.org bibliography application.

iso639 codes and the English names are derived from the ISO 639-2 codes located at
http://lcweb.loc.gov/standards/iso639-2/langcodes.html

Where there are synonyms in the 3 letter codes, the terminology code has been chosen.

Priority is user-configurable. However, the defaults are -
1. Languages frequently used in writing about Ernst Juenger
2. Languages with an ISO 639-1 code
3. All other languages
4. Not used.

Priority field will be used by the UI to present language choices to the user.
Languages have been prioritised so that users will be presented initially with a 
short list of languages to assign to a media item, thus retaining a degree of user
friendliness. However, they will also have all reasonable language choices (minus dialects)
only a couple of clicks away.
-->

<langlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="languageSchema.xsd">
        <language iso639="aar" priority="2" engName="Afar" />
        <language iso639="abk" priority="2" engName="Abkhazian" />
        <language iso639="ace" priority="3" engName="Achinese" />
        <language iso639="ach" priority="3" engName="Acoli" />
        <language iso639="ada" priority="3" engName="Adangme" />
        <language iso639="afa" priority="3" engName="Afro-Asiatic (Other)" />
        <language iso639="afh" priority="3" engName="Afrihili" />
        <language iso639="afr" priority="2" engName="Afrikaans" />
        <language iso639="aka" priority="3" engName="Akan" />
        <language iso639="akk" priority="3" engName="Akkadian" />
        <language iso639="ale" priority="3" engName="Aleut" />
        <language iso639="alg" priority="3" engName="Algonquian languages" />
        <language iso639="amh" priority="2" engName="Amharic" />
        <language iso639="ang" priority="3" engName="English, Old (ca.450-1100)" />
        <language iso639="apa" priority="3" engName="Apache languages" />
        <language iso639="ara" priority="2" engName="Arabic" />
        <language iso639="arc" priority="3" engName="Aramaic" />
        <language iso639="hye" priority="2" engName="Armenian" />
        <language iso639="arn" priority="3" engName="Araucanian" />
        <language iso639="arp" priority="3" engName="Arapaho" />
        <language iso639="art" priority="3" engName="Artificial (Other)" />
        <language iso639="arw" priority="3" engName="Arawak" />
        <language iso639="asm" priority="2" engName="Assamese" />
        <language iso639="ast" priority="3" engName="Asturian; Bable" />
        <language iso639="ath" priority="3" engName="Athapascan languages" />
        <language iso639="aus" priority="3" engName="Australian languages" />
        <language iso639="ava" priority="3" engName="Avaric" />
        <language iso639="ave" priority="2" engName="Avestan" />
        <language iso639="awa" priority="3" engName="Awadhi" />
        <language iso639="aym" priority="2" engName="Aymara" />
        <language iso639="aze" priority="2" engName="Azerbaijani" />
        <language iso639="bad" priority="3" engName="Banda" />
        <language iso639="bai" priority="3" engName="Bamileke languages" />
        <language iso639="bak" priority="2" engName="Bashkir" />
        <language iso639="bal" priority="3" engName="Baluchi" />
        <language iso639="bam" priority="3" engName="Bambara" />
        <language iso639="ban" priority="3" engName="Balinese" />
        <language iso639="eus" priority="2" engName="Basque" />
        <language iso639="bas" priority="3" engName="Basa" />
        <language iso639="bat" priority="3" engName="Baltic (Other)" />
        <language iso639="bej" priority="3" engName="Beja" />
        <language iso639="bel" priority="2" engName="Belarusian" />
        <language iso639="bem" priority="3" engName="Bemba" />
        <language iso639="ben" priority="2" engName="Bengali" />
        <language iso639="ber" priority="3" engName="Berber (Other)" />
        <language iso639="bho" priority="3" engName="Bhojpuri" />
        <language iso639="bih" priority="2" engName="Bihari" />
        <language iso639="bik" priority="3" engName="Bikol" />
        <language iso639="bin" priority="3" engName="Bini" />
        <language iso639="bis" priority="2" engName="Bislama" />
        <language iso639="bla" priority="3" engName="Siksika" />
        <language iso639="bnt" priority="3" engName="Bantu (Other)" />
        <language iso639="bod" priority="2" engName="Tibetan" />
        <language iso639="bos" priority="2" engName="Bosnian" />
        <language iso639="bra" priority="3" engName="Braj" />
        <language iso639="bre" priority="2" engName="Breton" />
        <language iso639="btk" priority="3" engName="Batak (Indonesia)" />
        <language iso639="bua" priority="3" engName="Buriat" />
        <language iso639="bug" priority="3" engName="Buginese" />
        <language iso639="bul" priority="2" engName="Bulgarian" />
        <language iso639="cad" priority="3" engName="Caddo" />
        <language iso639="cai" priority="3" engName="Central American Indian (Other)" />
        <language iso639="car" priority="3" engName="Carib" />
        <language iso639="cat" priority="2" engName="Catalan" />
        <language iso639="cau" priority="3" engName="Caucasian (Other)" />
        <language iso639="ceb" priority="3" engName="Cebuano" />
        <language iso639="cel" priority="3" engName="Celtic (Other)" />
        <language iso639="ces" priority="2" engName="Czech" />
        <language iso639="cha" priority="2" engName="Chamorro" />
        <language iso639="chb" priority="3" engName="Chibcha " />
        <language iso639="che" priority="2" engName="Chechen " />
        <language iso639="chg" priority="3" engName="Chagatai" />
        <language iso639="chk" priority="3" engName="Chuukese" />
        <language iso639="chm" priority="3" engName="Mari" />
        <language iso639="chn" priority="3" engName="Chinook jargon" />
        <language iso639="cho" priority="3" engName="Choctaw" />
        <language iso639="chp" priority="3" engName="Chipewyan" />
        <language iso639="chr" priority="3" engName="Cherokee" />
        <language iso639="chu" priority="2" engName="Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic" />
        <language iso639="chv" priority="2" engName="Chuvash" />
        <language iso639="chy" priority="3" engName="Cheyenne" />
        <language iso639="cmc" priority="3" engName="Chamic languages" />
        <language iso639="cop" priority="3" engName="Coptic" />
        <language iso639="cor" priority="2" engName="Cornish" />
        <language iso639="cos" priority="2" engName="Corsican" />
        <language iso639="cpe" priority="3" engName="Creoles and pidgins, English based (Other)" />
        <language iso639="cpf" priority="3" engName="Creoles and pidgins, French-based (Other)" />
        <language iso639="cpp" priority="3" engName="Creoles and pidgins, Portuguese-based (Other) " />
        <language iso639="cre" priority="3" engName="Cree" />
        <language iso639="crp" priority="3" engName="Creoles and pidgins (Other)" />
        <language iso639="cus" priority="3" engName="Cushitic (Other)" />
        <language iso639="cym" priority="2" engName="Welsh" />
        <language iso639="dak" priority="3" engName="Dakota" />
        <language iso639="dan" priority="2" engName="Danish " />
        <language iso639="day" priority="3" engName="Dayak" />
        <language iso639="del" priority="3" engName="Delaware" />
        <language iso639="den" priority="3" engName="Slave (Athapascan)" />
        <language iso639="deu" priority="1" engName="German" />
        <language iso639="dgr" priority="3" engName="Dogrib" />
        <language iso639="din" priority="3" engName="Dinka" />
        <language iso639="div" priority="3" engName="Divehi" />
        <language iso639="doi" priority="3" engName="Dogri" />
        <language iso639="dra" priority="3" engName="Dravidian (Other)" />
        <language iso639="dua" priority="3" engName="Duala" />
        <language iso639="dum" priority="3" engName="Dutch, Middle (ca.1050-1350)" />
        <language iso639="dyu" priority="3" engName="Dyula" />
        <language iso639="dzo" priority="2" engName="Dzongkha" />
        <language iso639="efi" priority="3" engName="Efik" />
        <language iso639="egy" priority="3" engName="Egyptian (Ancient)" />
        <language iso639="eka" priority="3" engName="Ekajuk" />
        <language iso639="ell" priority="2" engName="Greek, Modern (1453-)" />
        <language iso639="elx" priority="3" engName="Elamite" />
        <language iso639="eng" priority="1" engName="English" />
        <language iso639="enm" priority="3" engName="English, Middle (1100-1500)" />
        <language iso639="epo" priority="2" engName="Esperanto" />
        <language iso639="est" priority="2" engName="Estonian" />
